# Site settings
title: zVPS Blog
email: support@zvps.uk
description: "zVPS.uk nForced Website Hosting Limited Blog"
baseurl: ""
url: "http://blog.zvps.uk"
twitter_username: _zVPS
github_username:  zVPS

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments